### ISSUE TITLE
Wow JS mentioned in the README.md?

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/animate_css#1]
It doesn't look like this module is related to WOW JS, but there are a few mentions of it in the README.md file. Is this intentional?

**Comment by biolithic** [comment]
This module is a requirement for WOW JS module for Backdrop.  If you install this module "nothing will happen!  Panic!" (it just includes scripts for people to use in custom modules) but if you install WOW JS module as well, then you can see some sample effects of this module on your site (or change settings).

I just wanted to use the WOW JS library in a 3rd party way, but I tried to make it open for everybody.  I can take out the text if you want.

**Comment by quicksketch** [comment]
Ah! I was confused by the mention in the README.md but it wasn't a dependency in the .info file. So sounds like it's all intentional. Maybe clarify that WOW JS module demonstrates the functionality in this module. But, minor issue. Thanks!
